name: Test

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-gi \
            python3-venv \
            gir1.2-adw-1 \
            gir1.2-camel-1.2 \
            gir1.2-edataserver-1.2 \
            gir1.2-glib-2.0 \
            gir1.2-gtk-4.0 \
            xvfb

      - name: Run checks
        run: |
          python3 -m venv .venv --system-site-packages
          xvfb-run -a ./scripts/check.sh
